services:
  # Frontend static site configuration
  - type: web
    name: finance-chatbot
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build:safe
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://finance-chatbot-api.onrender.com
    routes:
      - type: redirect
        source: /index.html
        destination: /
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
  
  # Backend API service configuration
  - type: web
    name: finance-chatbot-api
    runtime: node
    rootDir: backend
    plan: free # Specify free plan (wake on request)
    buildCommand: npm install 
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        value: AIzaSyBB8eg_6VCS9OJWC_aBHL4b1n2UOv8b9qo
      - key: ALLOWED_ORIGINS
        value: https://finance-chatbot.onrender.com
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
